version: '3'

services:
  mongodb:
    image: mongo
    hostname: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lappis
      - MONGO_INITDB_ROOT_PASSWORD=lappis
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
