name: tf-gces

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: read-all|write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Set up Poetry 1.3.2
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.3.2"
    - run: ls -la
    - run: poetry --version

