name: tf-gces

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Set up Poetry 1.3.2
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.3.2"
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        run: poetry run pytest tests    
      - name: Run lint
        run: poetry run pylint --fail-under=7 src
      - name: Run build
        run: poetry build

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Doxygen 
        run: |
          sudo apt-get update
          sudo apt-get install doxygen
          doxygen Doxyfile
          doxygen -v
      - name: Set up Breathe 4.34.0
        run: |
          python -m pip install --upgrade pip
          pip install breathe==4.34.0
      - name: Set up Sphinx 6.1.3
        run: pip install sphinx==6.1.3
      - run: ls -la
      - name: Generate documentarion
        run: sphinx-build -b html . ./docs
      - run: ls -la

